#!/usr/bin/env python3
"""Draft Fig. 1 as three panels composed from the other draft generators (exploration, not yet in the paper).

(A) the agent-institution Coleman boat (gen_coleman_boat.py) and (B) nested systems around interacting agents,
with the 66 mechanisms as one ring (gen_rings_taxonomy.py).
Each source's CSS classes and element ids are prefixed so the panels cannot collide.
Run from manuscript/:  python3 scripts/gen_fig1_multipanel.py
"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DRAFTS = os.path.join(HERE, '..', 'figs', 'drafts')
OUT = os.path.join(DRAFTS, 'figure1_multipanel.html')
INK, MUTED = '#3F4D5A', '#6B7787'

SOURCES = {  # panel: (generator, html, crop viewBox or None for the full figure)
    'a': ('gen_coleman_boat.py', 'figure_coleman-boat.html', None),
    'b': ('gen_rings_taxonomy.py', 'figure_rings-taxonomy.html', None),
}

def extract(path, prefix):
    html = open(path, encoding='utf-8').read()
    m_style = re.search(r'<style>(.*?)</style>', html, re.S)
    style = m_style.group(1) if m_style else ''   # some figures style every element inline
    style = re.sub(r'html,body\{[^}]*\}|\.fig\{[^}]*\}', '', style)
    m = re.search(r'<svg\b[^>]*viewBox="([^"]*)"[^>]*>(.*)</svg>', html, re.S)
    vb, body = [float(x) for x in m.group(1).split()], m.group(2)
    ff = re.search(r'font-family="([^"]*)"', m.group(0)[:m.group(0).index('>') + 1])
    if ff:  # keep a font set on the source's outer <svg>, which the nested panel would otherwise lose
        body = f'<g font-family="{ff.group(1)}">{body}</g>'
    # prefix classes, ids, and id references
    style = re.sub(r'\.([A-Za-z][\w-]*)', lambda k: f'.{prefix}-{k.group(1)}', style)
    style = re.sub(r'(^|\})\s*text\s*\{', lambda k: f'{k.group(1)} .{prefix} text{{', style)
    body = re.sub(r'class="([^"]*)"', lambda k: 'class="' + ' '.join(f'{prefix}-{c}' for c in k.group(1).split()) + '"', body)
    body = re.sub(r'id="([^"]*)"', lambda k: f'id="{prefix}-{k.group(1)}"', body)
    body = re.sub(r'url\(#([^)]*)\)', lambda k: f'url(#{prefix}-{k.group(1)})', body)
    return style, vb, body

def main():
    for gen, _, _ in SOURCES.values():
        subprocess.run([sys.executable, os.path.join(HERE, gen)], check=True, stdout=subprocess.DEVNULL)
    W = 1000
    styles, parts = [], []
    # panel A: full width
    st, vb, body = extract(os.path.join(DRAFTS, SOURCES['a'][1]), 'a')
    styles.append(st)
    aw = W - 40; ah = aw * vb[3] / vb[2]
    parts.append(f'<text x="20" y="26" class="ptitle">A  From rules to outcomes, and back (after Coleman)</text>')
    parts.append(f'<svg x="20" y="36" width="{aw:.0f}" height="{ah:.0f}" viewBox="{" ".join(map(str, vb))}" class="a">{body}</svg>')
    y2 = 36 + ah + 56
    # panel B: nested systems with the taxonomy as one ring (full width, with its legend)
    st, vb, body = extract(os.path.join(DRAFTS, SOURCES['b'][1]), 'b')
    styles.append(st)
    bw = W - 40; bh = bw * vb[3] / vb[2]
    parts.append(f'<text x="20" y="{y2 - 14:.0f}" class="ptitle">B  Nested systems around interacting agents</text>')
    parts.append(f'<svg x="20" y="{y2:.0f}" width="{bw:.0f}" height="{bh:.0f}" viewBox="{" ".join(map(str, vb))}" class="b">{body}</svg>')
    H = y2 + bh + 10
    css = '\n'.join(styles) + f'\n  .ptitle{{font-family:"Helvetica Neue",Arial,sans-serif;font-size:20px;font-weight:800;fill:{INK};}}'
    html = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Draft Fig. 1: boat, rings, and taxonomy</title>
<!-- Draft generated by scripts/gen_fig1_multipanel.py from the boat, rings, and causal-chain drafts. -->
<style>{css}
  html,body{{margin:0;background:#fff;}} .fig{{width:{W}px;margin:0 auto;padding:12px;}}
</style></head><body><div class="fig">
<svg viewBox="0 0 {W} {H:.0f}" width="{W}" height="{H:.0f}" xmlns="http://www.w3.org/2000/svg">
{chr(10).join(parts)}
</svg></div></body></html>'''
    open(OUT, 'w', encoding='utf-8').write(html)
    # standalone SVG (extract_svg.py stops at the first nested </svg>, so write it here)
    svg_path = os.path.join(HERE, '..', 'figures', 'drafts', 'figure1_multipanel.svg')
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H:.0f}" width="{W}" height="{H:.0f}">'
           f'<defs><style type="text/css"><![CDATA[{css}]]></style></defs><rect width="100%" height="100%" fill="#fff"/>'
           + chr(10).join(parts) + '</svg>')
    open(svg_path, 'w', encoding='utf-8').write(svg)
    print('wrote', os.path.relpath(OUT), 'and', os.path.relpath(svg_path), f'{W}x{H:.0f}')

if __name__ == '__main__':
    main()
