#!/usr/bin/env python3
"""Fig. 2, agent-in-context: a compact, wide version of the layer stack in gen_multilayer.py.

The three isometric layers (governing institutions, agent-group interactions, individual model) sit closer together,
with each label to the right of its plate, between the top-down and bottom-up arrows. About half the height of the
original panel at the same printed text size. Reuses gen_multilayer's plates, node glyphs, arrows, and colors.
Run from manuscript/:  python3 scripts/gen_agent_in_context.py
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_multilayer as ml  # noqa: E402

OUT = os.path.join(HERE, '..', 'figs', 'figure_agent-in-context.html')
W, H = 440, 300
CX, PW, PH, TH = 128, 56, 23, 9
LAYERS = [  # (y, top fill, side fill, label lines, label color, node glyph)
    (52, ml.AM_TOP, ml.AM_SIDE, ['Governing', 'institutions'], ml.AM_D, ml.nodes_net),
    (150, ml.BL_TOP, ml.BL_SIDE, ['Agent–group', 'interactions'], ml.BL_D, ml.nodes_tri),
    (248, ml.VI_TOP, ml.VI_SIDE, ['Individual model', '(even if aligned)'], ml.VI_D, ml.nodes_one),
]

def build():
    o = [f'<svg viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" xmlns="http://www.w3.org/2000/svg" font-family="{ml.FONT}">',
         '<title>Agent-in-context</title>']
    # dotted guides joining the plate edges
    for (ya, *_), (yb, *_) in zip(LAYERS, LAYERS[1:]):
        for x in (CX - PW, CX + PW):
            o.append(f'<line x1="{x}" y1="{ya + TH + 2}" x2="{x}" y2="{yb - 2}" stroke="{ml.HAIR}" stroke-width="1" stroke-dasharray="2 4" opacity="0.7"/>')
    for y, top, side, label, col, nodes in LAYERS:
        o.append(ml.diamond(CX, y, PW, PH, TH, top, side, [], col, nodes))
    # arrows: top-down on the left, bottom-up to the right of the plates
    ytop, ybot = LAYERS[0][0] - PH - 6, LAYERS[-1][0] + PH + TH + 6
    ymid = (ytop + ybot) / 2
    o.append(ml.varrow(38, ytop, ybot, ml.AM_M))
    o.append(f'<text x="18" y="{ymid:.0f}" text-anchor="middle" font-size="15.5" font-weight="700" fill="{ml.AM_M}" transform="rotate(-90 18 {ymid:.0f})">Top-down</text>')
    o.append(ml.varrow(214, ybot, ytop, ml.VI_M))
    o.append(f'<text x="234" y="{ymid:.0f}" text-anchor="middle" font-size="15.5" font-weight="700" fill="{ml.VI_M}" transform="rotate(-90 234 {ymid:.0f})">Bottom-up</text>')
    # labels to the right
    for y, top, side, label, col, nodes in LAYERS:
        y0 = y + 5 - (len(label) - 1) * 9
        for i, line in enumerate(label):
            style = 'font-weight="400" font-style="italic"' if line.startswith('(') else 'font-weight="700"'
            o.append(f'<text x="262" y="{y0 + i * 19:.0f}" font-size="16.5" {style} fill="{col}">{ml.esc(line)}</text>')
    o.append('</svg>')
    return '\n'.join(o)

def main():
    svg = build()
    html = (f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><title>Agent-in-context</title>\n'
            f'<!-- Generated by scripts/gen_agent_in_context.py. -->\n'
            f'<style>html,body{{margin:0;background:#fff;}} .fig{{width:{W}px;margin:0 auto;padding:12px;}}</style></head>'
            f'<body><div class="fig">\n{svg}\n</div></body></html>')
    open(OUT, 'w', encoding='utf-8').write(html)
    print('wrote', os.path.relpath(OUT), f'{W}x{H}')

if __name__ == '__main__':
    main()
