#!/usr/bin/env python3
"""Compose the paper's Figs. 1-3 from the other figure generators.

Fig. 1  (A) the agent-in-context layer stack (left panel of gen_multilayer.py) beside
        (B) the nested systems around interacting agents, with the 66 mechanisms as a ring (gen_rings_taxonomy.py).
Fig. 2  the agent-institution Coleman boat (gen_coleman_boat.py).
Fig. 3  (A) the four cooperation-dilemma cards (gen_dilemmas.py), stacked two by two, beside
        (B) the design space of agent institutions (right panel of gen_multilayer.py).
Each source's CSS classes and element ids are prefixed so panels cannot collide. Writes figs/figureN_*.html and
figures/figureN_*.svg/.pdf. Run from manuscript/:  python3 scripts/gen_paper_figs123.py
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_fig1_multipanel import extract  # noqa: E402

FIGS, FIGURES, DRAFTS = (os.path.join(HERE, '..', d) for d in ('figs', 'figures', os.path.join('figs', 'drafts')))
INK = '#3F4D5A'
W = 1000
TITLE = f'.ptitle{{font-family:"Helvetica Neue",Arial,sans-serif;font-size:20px;font-weight:800;fill:{INK};}}'

def run(gen, env=None):
    subprocess.run([sys.executable, os.path.join(HERE, gen)], check=True, stdout=subprocess.DEVNULL,
                   cwd=os.path.join(HERE, '..'), env={**os.environ, **(env or {})})

def panel(src, key, crop, x, y, w, h):
    style, vb, body = extract(src, key)
    box = crop or vb
    return style, f'<svg x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" viewBox="{" ".join(map(str, box))}" class="{key}">{body}</svg>'

def write(name, title, styles, parts, height):
    css = '\n'.join(styles) + '\n  ' + TITLE
    body = '\n'.join(parts)
    html = (f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><title>{title}</title>\n'
            f'<!-- Generated by scripts/gen_paper_figs123.py; edit the source generators, not this file. -->\n'
            f'<style>{css}\n  html,body{{margin:0;background:#fff;}} .fig{{width:{W}px;margin:0 auto;padding:12px;}}\n</style></head>'
            f'<body><div class="fig">\n<svg viewBox="0 0 {W} {height:.0f}" width="{W}" height="{height:.0f}" xmlns="http://www.w3.org/2000/svg">\n{body}\n</svg></div></body></html>')
    open(os.path.join(FIGS, name + '.html'), 'w', encoding='utf-8').write(html)
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {height:.0f}" width="{W}" height="{height:.0f}">'
           f'<defs><style type="text/css"><![CDATA[{css}]]></style></defs><rect width="100%" height="100%" fill="#fff"/>{body}</svg>')
    svg_path = os.path.join(FIGURES, name + '.svg')
    open(svg_path, 'w', encoding='utf-8').write(svg)
    subprocess.run(['rsvg-convert', '--format', 'pdf1.5', '-o', os.path.join(FIGURES, name + '.pdf'), svg_path], check=True)
    print(f'wrote figs/{name}.html and figures/{name}.pdf ({W}x{height:.0f})')

def main():
    run('gen_multilayer.py'); run('gen_dilemmas.py'); run('gen_coleman_boat.py')
    run('gen_rings_taxonomy.py', {'RINGS_TEXT_SCALE': '1.35'})
    multi = os.path.join(FIGS, 'figure4_multi-layer-institutions.html')
    _, mvb, _ = extract(multi, 'm')
    MH = mvb[3]

    # Fig. 1: layer stack (A) beside the rings (B)
    rings = os.path.join(DRAFTS, 'figure_rings-taxonomy.html')
    _, rvb, _ = extract(rings, 'r')
    gap, head = 24, 44
    h = 742
    aw = h * 248 / MH
    bh = h - head; bw = bh * rvb[2] / rvb[3]
    x_b = aw + gap + (W - aw - gap - bw) / 2
    styles, parts = [], []
    st, p = panel(multi, 'a', (0, 0, 248, MH), 0, 0, aw, h); styles.append(st); parts.append(p)
    parts.append(f'<text x="{x_b + 4:.1f}" y="{28 * h / MH:.1f}" class="ptitle">B  Nested systems around interacting agents</text>')
    st, p = panel(rings, 'b', None, x_b, head, bw, bh); styles.append(st); parts.append(p)
    write('figure1_agents-in-context', 'Fig. 1: agents in context', styles, parts, h + 4)

    # Fig. 2: the Coleman boat, full width
    boat = os.path.join(DRAFTS, 'figure_coleman-boat.html')
    _, bvb, _ = extract(boat, 'c')
    st, p = panel(boat, 'c', None, 0, 0, W, W * bvb[3] / bvb[2])
    write('figure2_coleman-boat', 'Fig. 2: a Coleman boat for agent institutions', [st], [p], W * bvb[3] / bvb[2])

    # Fig. 3: dilemma cards two by two (A) beside the design space (B)
    cards = os.path.join(FIGS, 'figure2_four-cooperation-dilemmas.html')
    MARGIN, CARD_W, GAP, TOP, CARD_H = 18, 297, 18, 20, 442
    cw, ch, cg = CARD_W + 4, CARD_H + 4, 14
    grid_w, grid_h = 2 * cw + cg, 2 * ch + cg
    title_band = 66
    H3 = (W - 24) / (grid_w / (grid_h + title_band) + 472 / MH)
    s_a = H3 / (grid_h + title_band)
    styles, parts = [], []
    parts.append(f'<text x="4" y="{28 * H3 / MH:.1f}" class="ptitle">A  Four cooperation dilemmas</text>')
    for i in range(4):
        cx = MARGIN + i * (CARD_W + GAP) - 2
        col, row = i % 2, i // 2
        x = (col * (cw + cg)) * s_a
        y = (title_band + row * (ch + cg)) * s_a
        st, p = panel(cards, f'd{i}', (cx, TOP - 2, cw, ch), x, y, cw * s_a, ch * s_a)
        if i == 0: styles.append(st)
        parts.append(p.replace(f'class="d{i}"', 'class="d0"').replace(f'd{i}-', 'd0-'))
    xa = grid_w * s_a + 24
    st, p = panel(multi, 'e', (248, 0, 472, MH), xa, 0, H3 * 472 / MH, H3); styles.append(st); parts.append(p)
    write('figure3_dilemmas-design-space', 'Fig. 3: cooperation dilemmas and the design space', styles, parts, H3 + 4)

if __name__ == '__main__':
    main()
