#!/usr/bin/env python3
"""Build the paper's standalone figures that are cut from, or composed of, other generators' output.

  figure_nested-rings       nested systems around interacting agents, with the 66 mechanisms as a ring
                            (gen_rings_taxonomy.py, text enlarged for print)          -> Fig. 1, introduction
  figure_agent-in-context   the layer stack (left panel of gen_multilayer.py)          -> Section 2, top-down / bottom-up
  figure_design-space       the design space of agent institutions (right panel of gen_multilayer.py) -> Section 3
  figure_coleman-boat       the agent-institution Coleman boat (gen_coleman_boat.py)   -> Section 5
Each source's CSS classes and element ids are prefixed so nothing collides. Writes figs/<name>.html and
figures/<name>.svg/.pdf. Run from manuscript/:  python3 scripts/gen_paper_figs.py
"""
import os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_fig1_multipanel import extract  # noqa: E402

FIGS, FIGURES, DRAFTS = (os.path.join(HERE, '..', d) for d in ('figs', 'figures', os.path.join('figs', 'drafts')))

def run(gen, env=None):
    subprocess.run([sys.executable, os.path.join(HERE, gen)], check=True, stdout=subprocess.DEVNULL,
                   cwd=os.path.join(HERE, '..'), env={**os.environ, **(env or {})})

def write(name, title, src, key, crop=None):
    css, vb, body = extract(src, key)
    box = crop or vb
    w, h = box[2], box[3]
    inner = f'<svg x="0" y="0" width="{w:.0f}" height="{h:.0f}" viewBox="{" ".join(map(str, box))}" class="{key}">{body}</svg>'
    html = (f'<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><title>{title}</title>\n'
            f'<!-- Generated by scripts/gen_paper_figs.py; edit the source generator, not this file. -->\n'
            f'<style>{css}\n  html,body{{margin:0;background:#fff;}} .fig{{width:{w:.0f}px;margin:0 auto;padding:12px;}}\n</style></head>'
            f'<body><div class="fig">\n<svg viewBox="0 0 {w:.0f} {h:.0f}" width="{w:.0f}" height="{h:.0f}" xmlns="http://www.w3.org/2000/svg">\n{inner}\n</svg></div></body></html>')
    open(os.path.join(FIGS, name + '.html'), 'w', encoding='utf-8').write(html)
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:.0f} {h:.0f}" width="{w:.0f}" height="{h:.0f}">'
           f'<defs><style type="text/css"><![CDATA[{css}]]></style></defs><rect width="100%" height="100%" fill="#fff"/>{inner}</svg>')
    svg_path = os.path.join(FIGURES, name + '.svg')
    open(svg_path, 'w', encoding='utf-8').write(svg)
    subprocess.run(['rsvg-convert', '--format', 'pdf1.5', '-o', os.path.join(FIGURES, name + '.pdf'), svg_path], check=True)
    print(f'wrote figs/{name}.html and figures/{name}.pdf ({w:.0f}x{h:.0f})')

def main():
    run('gen_coleman_boat.py')
    run('gen_rings_taxonomy.py', {'RINGS_TEXT_SCALE': '1.35'})
    run('gen_multilayer.py', {'PANEL_LETTERS': '0'})
    multi = os.path.join(FIGS, 'figure4_multi-layer-institutions.html')
    _, mvb, _ = extract(multi, 'm')
    write('figure_nested-rings', 'Nested systems around interacting agents', os.path.join(DRAFTS, 'figure_rings-taxonomy.html'), 'r')
    write('figure_agent-in-context', 'Agent-in-context', multi, 'a', (0, 0, 246, mvb[3]))
    write('figure_design-space', 'Design space of agent institutions', multi, 'd', (252, 0, mvb[2] - 252, mvb[3]))
    write('figure_coleman-boat', 'A Coleman boat for agent institutions', os.path.join(DRAFTS, 'figure_coleman-boat.html'), 'c')
    run('gen_multilayer.py')          # restore the combined figure with its A/B letters
    run('gen_rings_taxonomy.py')      # and the rings draft at its default text size

if __name__ == '__main__':
    main()
