#!/usr/bin/env python3
"""Orchestrator's pass-1 code-to-codebook mapping.

Reads only the independent GPT pass-1 code summaries and CODEBOOK_FINAL.md.
Writes one audit CSV per model under this directory.
"""
import collections
import csv
import json
import re
from pathlib import Path


HERE = Path(__file__).resolve().parent
TAX = HERE.parent.parent
MODELS = ("gpt-6-luna", "gpt-5.6-terra")

# Explicit decisions for labels whose wording combines or ambiguously names levers.
MANUAL = {
    "adjust agent memory depth": "NEW",
    "adjust decision randomness": "NEW",
    "induce confirmation bias": "NEW",
    "VCG incentive mechanism": "M64",
    "accessible independent arbitration": "M51",
    "adaptive commons governance": "M46",
    "adaptive punishment intensity": "M27",
    "adaptive backoff after congestion": "M41",
    "adaptive punishment for defection": "M27",
    "agent activity logging": "M03",
    "agent governance framework": "M46",
    "aggregate reputation information": "M05",
    "apology for norm repair": "M55",
    "appeal sanction decision": "M54",
    "appeal and error correction": "M54",
    "appeal of automated decision": "M54",
    "appeal sanction decisions": "M54",
    "assurance bond": "M28",
    "attribution and rollback infrastructure": "M56",
    "authorized agent interruption": "M35",
    "automatic conditional execution": "M29",
    "automatic fixed fine": "M16",
    "bandwidth restriction": "M36",
    "bind conduct through prior commitment": "M30",
    "binding conditional transfers": "M29",
    "blind reciprocal feedback": "M39",
    "bond forfeited on breach": "M28",
    "bonded challenge and adjudication": "M53",
    "bonded challenge of claimed outcome": "M53",
    "bonded challenge of claims": "M53",
    "bounded elected authority": "M44",
    "cap extraction and membership": "M36",
    "cap individual resource extraction": "M36",
    "cap individual resource use": "M36",
    "cap shared resource use": "M36",
    "capability-based access restriction": "M34",
    "cash reward for participation": "M22",
    "centralized auction allocation": "M65",
    "choose among governance regimes": "M45",
    "choose among sanctioning institutions": "M45",
    "choose sanctioning institution": "M45",
    "choose interaction partners": "M10",
    "choose among cooperative partners": "M10",
    "choose cooperative interaction partners": "M10",
    "choose partners by reputation": "M10",
    "collective liability for deviation": "M20",
    "collectively amend governance rules": "M42",
    "collectively set resource and membership rules": "M42",
    "communicate or commit publicly": "M33",
    "communication for coordination": "M33",
    "communication plus peer sanctions": "M33",
    "communication topology restriction": "M38",
    "compliance transparency and support": "M67",
    "condition benefits on conduct": "M22",
    "condition cooperation on others conduct": "M39",
    "condition transfers on performance": "M22",
    "conditional cooperation on observed conduct": "M39",
    "conditional fine threat": "M16",
    "conditional public good subsidy": "M17",
    "conditional reciprocal cooperation": "M39",
    "conduct-based risk premium": "M12",
    "configure market allocation rules": "M65",
    "constrain permitted actions ex ante": "M34",
    "contact notification and quarantine": "M09",
    "contagious future-partner punishment": "M40",
    "contractual conditional transfer": "M29",
    "contribute to enforcement fund": "M16",
    "contribution-based tax and subsidy": "M17",
    "coordinate peer sanctions": "M14",
    "coordinate through shared procedure": "M38",
    "coordinated turn taking": "M37",
    "costly peer monitoring": "M01",
    "credential and performance reputation": "M05",
    "cross perspective fact checking": "M06",
    "crowdsourced fact checking": "M06",
    "cryptographic access control": "M34",
    "cultural no-take norm": "M58",
    "deadline-triggered disclosure": "M01",
    "democratic payoff rule adoption": "M42",
    "dense network norm enforcement": "M38",
    "detect and isolate collusive agents": "M09",
    "detect group collusion": "M01",
    "direct punishment": "M14",
    "disagreement escalation": "M51",
    "disclosure-conditioned amnesty": "M47",
    "disclosure-for-leniency": "M47",
    "distributed peer moderation": "M06",
    "escalate sanctions for repeated violations": "M27",
    "escalate uncertain decisions": "M51",
    "establish shared rules and authority": "M42",
    "evolved cooperative motivation": "M59",
    "exchange equal time credits": "M63",
    "exclude deviator from group": "M08",
    "explain applicable norm": "M58",
    "external stop authority": "M35",
    "externality pricing": "M17",
    "fair shared access scheduling": "M37",
    "filter extreme contributions": "M43",
    "filter harmful sanctions": "M50",
    "first reporter leniency": "M47",
    "fixed cost on detected deviation": "M16",
    "forfeit collateral on breach": "M28",
    "formalize conditional cooperation": "M39",
    "formalize reciprocal obligations": "M29",
    "gifting transfer": "M21",
    "gossip based partner exclusion": "M10",
    "gossip-based reputation": "M07",
    "govern shared memory updates": "M02",
    "govern shared memory selection": "M02",
    "governance graph sanctions": "M16",
    "graduated access restrictions": "M27",
    "graduated penalty for deviation": "M27",
    "graduated response to deviation": "M27",
    "graph anomaly intervention": "M01",
    "group expulsion": "M08",
    "group performance bonus": "M22",
    "honest quorum consensus": "M43",
    "immediate misreport penalty": "M16",
    "impose cost after deviation": "M14",
    "impose cost for norm violation": "M14",
    "impose escalating cost for breach": "M27",
    "impose pre-agreed cost for breach": "M29",
    "impose social cost for default": "M18",
    "inactivity stake drain": "M28",
    "institutional oversight and audit": "M01",
    "interaction monitoring": "M01",
    "intrinsic cooperative reward": "M59",
    "intrinsic norm based incentives": "M59",
    "joint liability": "M20",
    "learn norms from public sanctions": "M61",
    "learned reward and punishment": "M17",
    "learned tax and allowance": "M17",
    "liability for imposed harm": "M19",
    "limit permitted actions by default": "M34",
    "limited third-party observation": "M01",
    "limited third-party observability": "M01",
    "majority-contingent juror stake": "M53",
    "make cheating detectable": "M01",
    "make reversal costly after commitment": "M30",
    "managerial punishment authority": "M16",
    "mandatory tool authorization": "M34",
    "marginal-contribution reward sharing": "M25",
    "market resource allocation rules": "M65",
    "market search and matching": "M65",
    "match contributions nonlinearly": "M64",
    "mediated disclosure timetable": "M01",
    "membership-contingent cooperation": "M13",
    "milestone-based coordination protocol": "M38",
    "monitor and isolate misbehavior": "M09",
    "monitor and route around": "M10",
    "multi-run collusion audit": "M01",
    "network rewiring": "M10",
    "network topology design": "M38",
    "newcomer identity dues": "M13",
    "nonmember market penalty": "M13",
    "norm-setting message board": "M58",
    "observe and record conduct": "M01",
    "ostracism of defectors": "M08",
    "participatory resource allocation": "M42",
    "partner choice and severance": "M10",
    "pay for verified discoveries": "M22",
    "peer agreed sanctions": "M14",
    "peer conditional reward": "M21",
    "peer cost imposition": "M14",
    "peer norm pressure": "M18",
    "peer norm sanctions": "M14",
    "peer review and public scrutiny": "M06",
    "peer territorial exclusion": "M13",
    "peer-information exposure": "M18",
    "penalty for noncompliant traffic": "M16",
    "permanent access ban": "M08",
    "pool resources for mutual support": "M63",
    "preplay communication": "M33",
    "pre-play communication": "M33",
    "proactive content restriction": "M35",
    "prune compromised communication edges": "M10",
    "public announcement commitment": "M33",
    "public append-only record": "M03",
    "public conduct disclosure": "M01",
    "public conduct reputation": "M05",
    "public disapproval signal": "M18",
    "public judgment record": "M05",
    "public nonbinding pledge": "M33",
    "public record of conduct": "M05",
    "public record of past conduct": "M05",
    "public reputation conditioning": "M12",
    "publicize violation": "M18",
    "publicize vulnerability information": "M18",
    "punish failed enforcement": "M49",
    "punish failure to enforce": "M49",
    "quorum-based replication": "M43",
    "quorum agreement rule": "M43",
    "quota and adaptive throttling": "M36",
    "rank based team rewards": "M26",
    "rank-contingent prize": "M26",
    "rate limit access": "M36",
    "reciprocal contribution access": "M41",
    "recommendation-based exposure nudge": "M60",
    "reconciliation after harm": "M55",
    "redesign reward to favor contribution": "M64",
    "refund deposit upon compliant return": "M28",
    "remove agents temporarily after attack": "M09",
    "remove or avoid uncooperative partners": "M10",
    "reporting linked incentives": "M48",
    "reputation based exclusion": "M12",
    "reputation based partner selection": "M10",
    "reputation conditioned cooperation": "M40",
    "reputation conditioned rewards": "M12",
    "reputation penalty on sales": "M12",
    "reputation threshold for access": "M12",
    "reputation-based partner selection": "M10",
    "reputation-conditioned aid": "M40",
    "reputation-earned permissions": "M12",
    "resource-use cap": "M36",
    "restrict access after conduct": "M12",
    "restrict permitted actions ex ante": "M34",
    "restrictive quality control": "M35",
    "review and reverse erroneous decisions": "M54",
    "reward contribution or performance": "M22",
    "reward truthful conduct and penalize falsehood": "M64",
    "rewarded violation reporting": "M48",
    "role specification and verification": "M34",
    "rotating access allocation": "M37",
    "rotating reciprocal contributions": "M37",
    "runtime rule enforcement": "M35",
    "sanctioning institution": "M16",
    "score-based strategy reproduction": "M62",
    "select or rewire partners": "M10",
    "self-defeating attack cost": "M17",
    "self-funded abstinence deposit": "M28",
    "set receiver action for failed authentication": "M34",
    "shared ownership and profit sharing": "M25",
    "signed transaction commitment": "M29",
    "simultaneous review reveal": "M06",
    "specify delegation boundaries": "M34",
    "stable centralized matching": "M65",
    "stake forfeiture on misconduct": "M28",
    "stake-based alignment": "M25",
    "stake-weighted voting": "M42",
    "standardize sanction decisions": "M16",
    "state rollback": "M56",
    "success-biased imitation": "M62",
    "tag-out exclusion": "M09",
    "tax and redistribution": "M17",
    "tax-message allocation rule": "M64",
    "temporary exclusion": "M09",
    "third party dispute adjudication": "M51",
    "third party dispute mediation": "M52",
    "third party observation": "M01",
    "third party resolves disputes": "M51",
    "third-party dispute ruling": "M51",
    "third-party mediation": "M52",
    "third-party punishment": "M15",
    "threshold switched reward and penalty": "M17",
    "threshold-contingent refund": "M32",
    "thresholded agent termination": "M08",
    "token-holder rulemaking": "M42",
    "trajectory risk escrow": "M31",
    "transparent harvest reporting": "M01",
    "universalization prompt": "M59",
    "validator participation reward": "M22",
    "validator reward and penalty": "M17",
    "validator rewards and penalties": "M17",
    "verbal peer criticism": "M18",
    "verified-work contingent payment": "M22",
    "verify identity or conduct": "M01",
    "voluntary future commitment": "M30",
    "voted governance constitution": "M42",
    "warning before escalation": "M27",
    "warrant backed performance": "M19",
    "weight many small contributions": "M64",
    "weight messages by confidence": "M43",
    "worker policing": "M14",
    "Byzantine-robust answer aggregation": "M43",
    "access conditional on compliance": "M12",
    "adaptive backoff after congestion": "M41",
    "adaptive external incentives": "M17",
    "adaptive punishment for defection": "M27",
    "adaptive tax on harmful action": "M17",
    "allocate budget by participation": "M22",
    "allocate equal service shares": "M36",
    "allocate through central auction": "M65",
    "appeal and error correction": "M54",
    "appeal of automated decision": "M54",
    "appeal sanction decisions": "M54",
    "assign accident liability": "M19",
    "assign decentralized reputations": "M05",
    "attach public fact checks": "M06",
    "attributable contribution attestation": "M04",
    "authenticated access control with audit": "M34",
    "authenticated delegated access": "M34",
    "authorize system interruption": "M35",
    "automated failure attribution": "M57",
    "automatically enforced conditional transfer": "M29",
    "automatically execute conditions": "M29",
    "bid-based task allocation": "M65",
    "binary exclusion list": "M11",
    "bind conditional transfers": "M29",
    "bind negotiated agreements": "M29",
    "bind signed transaction mandates": "M29",
    "binding conditional transfer contract": "M29",
    "budgeted runtime audit scheduling": "M01",
    "build dense civic networks": "M38",
    "calibrate collective decisions": "M43",
    "cap on per-agent resource use": "M36",
    "cap per-group resource use": "M36",
    "central identity certification": "M04",
    "centralized matching rule": "M65",
    "certified agent directory": "M04",
    "collective enforcement against dominance": "M50",
    "collective liability for default": "M20",
    "collective monitoring and sanctions": "M01",
    "collective override of protocol outcome": "M42",
    "collective rule-making and vote": "M42",
    "collective rulemaking": "M42",
    "collectively adopt governance rules": "M42",
    "collectively adopt rules": "M42",
    "collectively approve sanctions": "M42",
    "collectively authored governance rules": "M42",
    "collectively chosen legal sanction": "M16",
    "collectively chosen peer sanctions": "M14",
    "combine reputation evidence": "M43",
    "compensating transaction rollback": "M56",
    "competence-based task outsourcing": "M65",
    "compliance support and review": "M67",
    "computed reputation score": "M05",
    "condition help on generosity": "M40",
    "condition help on observed conduct": "M39",
    "conditional material incentives": "M22",
    "conditional reciprocal response": "M39",
    "conditional reintegration after exclusion": "M55",
    "conditionally reward validators": "M22",
    "configure market institutions": "M65",
    "consensus veto on changes": "M42",
    "cooperation-favoring reward redesign": "M64",
    "cooperative default option": "M60",
    "coordinate channel access": "M37",
    "coordinate resource schedules": "M37",
    "correlated stake forfeiture": "M20",
    "cost imposed for deviation": "M14",
    "costly peer penalties": "M14",
    "costly public commitment": "M33",
    "costly punishment of defection": "M14",
    "costly punishment of unfairness": "M14",
    "costly self-binding commitment": "M30",
    "credible punishment for breach": "M29",
    "credit payment for network forwarding": "M63",
    "cross-group validate fact checks": "M06",
    "crowdsourced violation adjudication": "M51",
    "cryptographic fault attribution": "M57",
    "decentralized community governance": "M42",
    "decentralized ethical consensus": "M42",
    "defection-contingent punishment": "M14",
    "delegate peer moderation": "M06",
    "dense reciprocal network": "M38",
    "deposit forfeited on breach": "M28",
    "deposit refunded on return": "M28",
    "detect group collusion": "M01",
    "discard extreme inputs": "M43",
    "elect bounded leadership": "M44",
    "elect democratic compliance monitor": "M44",
    "elected group leadership": "M44",
    "enable pre-play communication": "M33",
    "enforce access-control policies": "M34",
    "enforce compliance state transitions": "M35",
    "enforce content quality rules": "M35",
    "enforce permitted control flows": "M34",
    "enforce sender reputation threshold": "M12",
    "enforce transaction warranties": "M19",
    "enforceable bilateral contract": "M29",
    "escalate sanctions by violation": "M27",
    "escalating account blocking": "M27",
    "escalating account restrictions": "M27",
    "escalating audit and arbitration": "M27",
    "escalating delay after failure": "M27",
    "escalating fine and suspension": "M27",
    "escalating fines and suspension": "M27",
    "escalating sanctions for violations": "M27",
    "escrowed service settlement": "M31",
    "evolutionary selection of strategies": "M62",
    "exclude based on gossip": "M10",
    "expiring access right": "M34",
    "explain rule enforcement": "M58",
    "explicit behavioral rules": "M58",
    "express peer disapproval": "M18",
    "externality tax and allowance": "M17",
    "externally halt agent actions": "M35",
    "filter antisocial punishment": "M50",
    "fine for detected violation": "M16",
    "fixed cost on violation": "M16",
    "fixed interaction network": "M38",
    "forfeit escrow on breach": "M31",
    "forfeit funds on breach": "M28",
    "forfeit relationship-specific rents": "M28",
    "fund centralized sanctions": "M16",
    "generalized reciprocal contribution": "M39",
    "global reputation score": "M05",
    "gossip-based reputation and exclusion": "M07",
    "graduated service degradation": "M27",
    "hard action constraint filtering": "M34",
    "hide reciprocal feedback": "M39",
    "identifiable participant conduct": "M04",
    "imitate successful strategies": "M62",
    "imitate successful strategy": "M62",
    "immunity for first disclosure": "M47",
    "impose expected damages": "M19",
    "incentive-compatible allocation rule": "M64",
    "independent appeal adjudication": "M54",
    "individual resource quota": "M36",
    "inspection for compliance transparency": "M01",
    "institutional design principles": "M46",
    "institutional self-selection": "M45",
    "insured stake for agent conduct": "M28",
    "intercept prohibited actions": "M35",
    "internalize moral rewards": "M59",
    "internalized norm for cooperation": "M59",
    "intrinsic reward for reputation use": "M59",
    "label message source": "M04",
    "learn authoritative norms": "M61",
    "learn from public sanctions": "M61",
    "learn local reputation assignments": "M61",
    "learn norms from public sanctions": "M61",
    "learn reputation-based interaction": "M61",
    "learn reputation-based policy": "M61",
    "learn shared institutional norms": "M61",
    "learning incentive for imitation": "M62",
    "least-privilege access control": "M34",
    "limit repeated reversal actions": "M35",
    "limited third-party observability": "M01",
    "log agent activity": "M03",
    "make actors identifiable": "M04",
    "make protocol cheating detectable": "M01",
    "mandatory entry requirement": "M13",
    "mandatory operational checklist": "M58",
    "match dispersed contributions": "M22",
    "mediate disputes": "M52",
    "mediate marketplace disputes": "M52",
    "milestone-based recognition reward": "M23",
    "minimal reward redistribution": "M25",
    "monitor and isolate colluders": "M09",
    "monitor and isolate misbehavior": "M09",
    "monitor conduct for deviation": "M01",
    "monitor latent coordination signals": "M02",
    "multi-source partner reputation": "M05",
    "mutual aid risk pool": "M63",
    "mutual peer accountability": "M20",
    "nested rulemaking authority": "M46",
    "norm creation and diffusion": "M58",
    "observe third-party interactions": "M01",
    "outcome-contingent payment contract": "M29",
    "output-contingent pay": "M22",
    "partner choice and reciprocity": "M10",
    "payment conditional on conservation": "M22",
    "payment conditional on delivery": "M22",
    "peer compliance review": "M06",
    "peer fine for defection": "M14",
    "peer fine for low contribution": "M14",
    "peer fine for norm violation": "M14",
    "peer normative pressure": "M18",
    "peer policing of reproduction": "M14",
    "peer punishment of defection": "M14",
    "peer punishment of norm violation": "M14",
    "peer rewards after cooperation": "M21",
    "peer rewards and sanctions": "M14",
    "peer sanction for default": "M14",
    "persistent agent identity credential": "M04",
    "persistent private agent memory": "M39",
    "planner-assigned rewards and penalties": "M17",
    "platform reputation ratings": "M05",
    "police reproductive deviation": "M14",
    "pre-agreed breach penalty": "M29",
    "pre-play communication": "M33",
    "priced unilateral contract exit": "M29",
    "processing cost per request": "M17",
    "prompt universalized reasoning": "M59",
    "prompted social deliberation": "M59",
    "protocol incentive adjustment": "M17",
    "protocol-based trust constraints": "M34",
    "public commitment announcement": "M33",
    "public disclosure of resource use": "M01",
    "public promise before action": "M33",
    "public record of past conduct": "M05",
    "public sanction norm learning": "M61",
    "public verifiable issuance log": "M03",
    "publicize resource use": "M01",
    "publicize security vulnerabilities": "M18",
    "publicize violations": "M18",
    "publish certified performance records": "M05",
    "publish revoked credential list": "M11",
    "publish vulnerability reporting channel": "M48",
    "punish enforcement failures": "M49",
    "punish to induce cooperation": "M14",
    "quorum agreement rule": "M43",
    "rank-based team rewards": "M26",
    "receiver-attested action receipt": "M03",
    "reciprocal community currency": "M63",
    "reciprocal response strategy": "M39",
    "reciprocate service provision": "M39",
    "reciprocate upload with service": "M39",
    "refund bonus on failed threshold": "M32",
    "refuse service to listed source": "M11",
    "relationship severance for defection": "M10",
    "remove deviator from group": "M08",
    "remove intruder access": "M08",
    "remove violating community": "M08",
    "repair norms through apology": "M55",
    "reputation-based cooperation learning": "M61",
    "reputation-based exclusion": "M12",
    "reputation-based indirect reciprocity": "M40",
    "reputation-based partner exclusion": "M10",
    "reputation-based partner selection": "M10",
    "reputation-based task allocation": "M12",
    "reputation-conditioned future benefit": "M12",
    "reputation-linked access control": "M12",
    "reputation-linked sales restriction": "M12",
    "required congestion backoff": "M41",
    "resample suspicious actions": "M35",
    "resilient peer communication network": "M38",
    "restoration of inflicted harm": "M55",
    "restore relationships after harm": "M55",
    "restrict permitted actions ex ante": "M34",
    "restrict permitted interactions": "M34",
    "retaliate against theft": "M14",
    "retaliation against punishers": "M50",
    "revoke trusted credential issuer": "M11",
    "reward conditional on conduct": "M22",
    "reward consensus reporting": "M48",
    "reward first self-report": "M47",
    "reward self-reporting": "M47",
    "reward violation reporting": "M48",
    "reward vulnerability reporting": "M48",
    "role-differentiating prompts": "M59",
    "rotate resource access": "M37",
    "sandbox untrusted code": "M35",
    "sandboxed agent economy": "M65",
    "scoped delegated credentials": "M34",
    "select collective constitution": "M42",
    "sender authentication policy": "M34",
    "separate oversight authority": "M50",
    "sever ties by reputation": "M10",
    "share penalty across group": "M20",
    "share reputational gossip": "M07",
    "share reputational warnings": "M07",
    "shared communication": "M33",
    "shared ownership of returns": "M25",
    "shared strategy prompt optimization": "M59",
    "signal and enforce rate limit": "M36",
    "signed agent capability registry": "M04",
    "simultaneously reveal feedback": "M06",
    "smart-contract task coordination": "M29",
    "social disapproval for noncontribution": "M18",
    "stable centralized matching": "M65",
    "stake forfeited for equivocation": "M28",
    "stake forfeiture for violation": "M28",
    "standardize sanction decisions": "M16",
    "standardized agent authorization claims": "M34",
    "standardized incident reporting": "M57",
    "status reward for contribution": "M23",
    "structure interaction network": "M38",
    "structured participation rule": "M38",
    "structured task delegation": "M34",
    "subsidize public contributions": "M22",
    "swift certain breach sanction": "M16",
    "switch away from deviator": "M10",
    "switch incentives by threshold": "M17",
    "tailored institutional rules": "M46",
    "tamper-evident audit trail": "M03",
    "tariff nonparticipants": "M13",
    "tax on harmful externality": "M17",
    "temporary activity restriction": "M09",
    "temporary service cutoff after failures": "M09",
    "third party adjudication": "M51",
    "third party behavioral observation": "M01",
    "third party mediation": "M52",
    "third party punishment": "M15",
    "third-party debate adjudication": "M51",
    "third-party dispute mediation": "M52",
    "third-party dispute resolution": "M51",
    "third-party handling of violations": "M15",
    "third-party obligation clearing": "M31",
    "threaten economic penalty": "M16",
    "transfer rewards to peers": "M21",
    "truthful reporting payment rule": "M64",
    "universalization prompt": "M59",
    "verified agent identity": "M04",
    "verified contribution-based rewards": "M22",
    "visible peer performance": "M05",
    "voluntarily commit to plans": "M30",
    "voluntary centralized sanctioning group": "M16",
    "voluntary commitment device": "M30",
    "voluntary future-plan commitment": "M30",
    "voluntary peer reward transfer": "M21",
    "voluntary sanctioning institution": "M45",
    "weight messages by confidence": "M43",
    "withhold benefit from noncontributor": "M22",
}


def classify(code):
    if code in MANUAL:
        return MANUAL[code]
    s = code.lower()
    # Main concepts, ordered from specific levers to broader families.
    if any(x in s for x in ("arbitr", "adjudicat", "judicial", "dispute resolution", "resolves disputes", "debate adjudication")): return "M51"
    if "mediat" in s: return "M52"
    if any(x in s for x in ("appeal", "error correction", "review and reverse")): return "M54"
    if any(x in s for x in ("bonded challenge", "fault proof")): return "M53"
    if any(x in s for x in ("leniency", "amnesty", "self-report", "self report", "first disclosure")): return "M47"
    if any(x in s for x in ("report", "bug bounty")): return "M48"
    if any(x in s for x in ("anti-social punishment", "antisocial punishment", "check on sanction", "retaliation against punishers", "oversight authority", "dominance")): return "M50"
    if any(x in s for x in ("failure to enforce", "enforcement failures", "failed enforcement", "metanorm")): return "M49"
    if any(x in s for x in ("rollback", "revert", "undoing", "compensating transaction", "state rollback")): return "M56"
    if any(x in s for x in ("apology", "reconciliation", "restoration", "restore relationship", "reintegration", "restitution", "repair harm", "norm repair")): return "M55"
    if any(x in s for x in ("failure attribution", "incident analysis", "incident reporting", "forensic")): return "M57"
    if any(x in s for x in ("public record", "record of past conduct", "reputation score", "reputation ratings", "reputation information", "reputation record", "computed reputation", "global reputation", "performance records")): return "M05"
    if "gossip" in s: return "M07"
    if any(x in s for x in ("reputation", "partner choice", "interaction partners", "cooperative partners", "switch away", "sever ties", "rewir")): return "M10"
    if any(x in s for x in ("revok", "blocklist", "exclusion list", "listed source")): return "M11"
    if any(x in s for x in ("reputation-based exclusion", "reputation based exclusion", "reputation-linked access", "reputation threshold", "access conditional", "access after conduct", "reputation penalty", "reputation-conditioned", "reputation conditioned", "reputation-earned")): return "M12"
    if any(x in s for x in ("membership", "nonmember", "non-member", "outsider", "territorial", "newcomer identity dues")): return "M13"
    if any(x in s for x in ("temporary", "quarantine", "suspend", "tag-out", "tag out", "cutoff", "service cutoff", "isolate")): return "M09"
    if any(x in s for x in ("expel", "ban", "remove deviator", "remove agent", "ostracism", "terminate", "agent termination")): return "M08"
    if any(x in s for x in ("liability", "damages", "warrant", "accident")): return "M19"
    if any(x in s for x in ("collective liability", "group liability", "share penalty", "correlated stake", "joint liability")): return "M20"
    if any(x in s for x in ("graduat", "escalat", "adaptive punishment", "warning before escalation")): return "M27"
    if any(x in s for x in ("stake", "deposit", "bond", "collateral", "forfeit", "inactivity stake", "insured stake")): return "M28"
    if any(x in s for x in ("escrow", "settlement", "obligation clearing")): return "M31"
    if any(x in s for x in ("assurance", "threshold-contingent refund", "refund bonus", "refund on failed threshold")): return "M32"
    if any(x in s for x in ("contract", "agreement", "conditional transfer", "transaction mandate", "automatic conditional execution", "execute conditions", "smart-contract")): return "M29"
    if any(x in s for x in ("commitment", "commit", "self-binding", "self binding", "future-plan", "future commitment", "voluntary future")): return "M30"
    if "third-party punishment" in s or "third party punishment" in s: return "M15"
    if any(x in s for x in ("peer punishment", "peer penalties", "peer fine", "peer sanction", "peer cost", "peer policing", "direct punishment", "cost imposed for deviation", "impose cost", "punish to induce", "punish defection", "punish violation", "costly punishment", "punishment of defection", "peer agreed sanctions", "retaliate")): return "M14"
    if any(x in s for x in ("fixed fine", "fine for", "economic penalty", "fine threat", "fund centralized sanctions", "centralized sanction", "sanctioning institution", "sanction authority", "sanction decisions", "automatic fine", "governance graph sanctions", "impose pre-agreed cost")): return "M16"
    if any(x in s for x in ("social cost", "peer pressure", "social disapproval", "disapproval", "shaming", "publicize violation", "publicize vulnerability", "criticism", "peer norm pressure", "peer normative pressure", "exposure")): return "M18"
    if any(x in s for x in ("tax", "subsidy", "externality pricing", "external incentive", "incentive adjustment", "processing cost", "fixed cost", "cost on violation", "cost on harmful")): return "M17"
    if any(x in s for x in ("peer reward", "gifting", "gift economy", "transfer rewards to peers", "reward transfer", "voluntary peer reward")): return "M21"
    if any(x in s for x in ("rank", "tournament", "rank-contingent")): return "M26"
    if any(x in s for x in ("status reward", "milestone recognition", "prestige")): return "M23"
    if any(x in s for x in ("profit sharing", "shared ownership", "reward sharing", "ownership of returns")): return "M25"
    if any(x in s for x in ("reward", "payment", "pay for", "cash reward", "bonus", "payoff", "incentive", "withhold benefit", "benefit on conduct", "allocate budget")): return "M22"
    if any(x in s for x in ("auction", "market", "matching", "task allocation", "bid-based")): return "M65"
    if any(x in s for x in ("reciprocity", "reciprocal", "reciprocate", "conditional cooperation", "condition cooperation on others")): return "M39"
    if any(x in s for x in ("imitation", "imitate", "evolutionary selection", "strategy reproduction", "strategy evolution")): return "M62"
    if any(x in s for x in ("mutual aid", "pool resources", "community currency", "time credits")): return "M63"
    if any(x in s for x in ("rotation", "turn taking", "turn-taking", "resource schedule", "channel access", "equal service shares")): return "M37"
    if any(x in s for x in ("quota", "resource-use cap", "resource use cap", "resource extraction", "bandwidth restriction", "rate limit", "throttl", "congestion")): return "M36"
    if any(x in s for x in ("network topology", "network rewiring", "dense network", "interaction network", "communication topology", "coordination protocol", "shared procedure", "structured participation", "civic network", "fixed interaction network", "interaction structure")): return "M38"
    if any(x in s for x in ("interrupt", "intercept", "halt", "sandbox", "resample", "runtime", "quality control", "content restriction", "action filtering", "stop authority")): return "M35"
    if any(x in s for x in ("access control", "authorization", "authorized", "credential", "delegat", "permitted action", "action restriction", "restrict permitted", "role specification", "authentication", "entry requirement", "control flow", "scoped", "agent directory", "access right")): return "M34"
    if any(x in s for x in ("monitor", "audit", "observe", "observation", "inspection", "detect", "make cheating detectable", "fact check", "fact-check", "transparency", "logging", "log agent", "compliance review")): return "M01"
    if any(x in s for x in ("communication", "preplay", "pre-play", "pledge", "public promise", "shared communication")): return "M33"
    if any(x in s for x in ("identity", "identifiable", "attribution", "message source")): return "M04"
    if any(x in s for x in ("log", "append-only", "audit trail", "record", "attestation", "receipt")): return "M03"
    if "reputation" in s: return "M05"
    if any(x in s for x in ("norm", "conduct standard", "checklist", "explain applicable")): return "M58"
    if any(x in s for x in ("elected", "elect ", "leadership")): return "M44"
    if any(x in s for x in ("governance", "rulemaking", "rule-making", "rule adoption", "collective rule", "voted governance", "consensus", "veto")): return "M42"
    if any(x in s for x in ("institutional choice", "choose among governance", "sanctioning institution")): return "M45"
    if any(x in s for x in ("adaptive governance", "nested rule", "tailored institutional", "institutional design")): return "M46"
    if any(x in s for x in ("universalization", "prompt", "intrinsic", "motivation", "moral reward", "deliberation", "reasoning")): return "M59"
    if any(x in s for x in ("default option", "nudge")): return "M60"
    if any(x in s for x in ("learn", "infer shared norms")): return "M61"
    if any(x in s for x in ("allocation rule", "incentive-compatible", "vcg", "contributions nonlinearly", "truthful reporting", "weight many small contributions")): return "M64"
    if any(x in s for x in ("resource state", "harvest reporting")): return "M66"
    if any(x in s for x in ("support", "assistance", "capacity")): return "M67"
    return "NEW"


def main():
    book = (TAX / "coding" / "CODEBOOK_FINAL.md").read_text(encoding="utf-8")
    definitions = {}
    for line in book.splitlines():
        match = re.match(r"- \*\*(M\d{2}) ([^*]+)\*\*: (.*)", line)
        if match:
            mid, name, definition = match.groups()
            definitions[mid] = (name, definition.split(" _Examples:")[0].strip())
    assert len(definitions) == 66, len(definitions)
    for model in MODELS:
        counts = collections.Counter()
        for batch in range(1, 5):
            path = HERE / model / f"pass1_batch{batch}_codes.json"
            for row in json.loads(path.read_text(encoding="utf-8")):
                counts[row["code"]] += row["n_instances"]
        rows = []
        for code, n in sorted(counts.items()):
            mid = classify(code)
            if mid == "NEW":
                reason = ("No final-codebook mechanism covers this distinct lever as named: "
                          f"{code}. It is retained as NEW for the author's ending-condition review.")
            else:
                name, definition = definitions[mid]
                reason = f"The code names {code}; it is closest to {mid} {name} because {definition[0].lower() + definition[1:] if definition else definition}"
                if not reason.endswith("."):
                    reason += "."
            rows.append({"open_code": code, "n_instances": n,
                         "mechanism_id_or_NEW": mid, "rationale": reason})
        path = HERE / model / "pass1_code_map.csv"
        with path.open("w", newline="", encoding="utf-8") as stream:
            writer = csv.DictWriter(stream, fieldnames=("open_code", "n_instances", "mechanism_id_or_NEW", "rationale"))
            writer.writeheader()
            writer.writerows(rows)
        news = [row["open_code"] for row in rows if row["mechanism_id_or_NEW"] == "NEW"]
        print(f"{model}: {len(rows)} open codes, {len(news)} NEW: {', '.join(news) if news else 'none'}")


if __name__ == "__main__":
    main()
